### ISSUE TITLE
SHEET POSITION CENTER -- NOT TO RIGHTMOST CORNER

### ISSUE THREAD

**Issue by madibalive** [gowong/material-sheet-fab#31]
Hi, it doesn't to allow flexible positioning , is there to override it , so instead to enlarging in the leftmost corner it on the center above the fab(which is also position at the center) 

Looking the source code it seem this is the method to override 
`setFabAnchor `

**Comment by gowong** [comment]
Hi,
It sounds like you're looking to center the FAB and have the sheet open directly above it. This isn't supported since it's not a pattern outlined in the [material design guidelines](https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions). 

If you'd like to add support for this yourself, a good place to start would be [`MaterialSheetAnimation.alignSheetWithFab()`](https://github.com/gowong/material-sheet-fab/blob/master/material-sheet-fab/src/main/java/com/gordonwong/materialsheetfab/animations/MaterialSheetAnimation.java#L66)

**Comment by madibalive** [comment]
thanks for the reply, i spent the last hours the last two hours trying to get it in effect ,
the instance member `sheet` in the `alignSheetWithFab` is private so extending the class seem not do anything 
```
// Set sheet's new coordinates (only if there is a change in coordinates because
		// setting the same coordinates can cause the view to "drift" - moving 0.5 to 1 pixels
		// around the screen)
                **// setting the sheet.setX(fab.coord[0] to the x cordinate of the fab** 

		if (rightDiff != 0) {  **// and removing this block of code should fix it i think**

			float sheetX = sheet.getX();
			// Align the right side of the sheet with the right side of the FAB if
			// doing so would not move the sheet off the screen
			if (rightDiff <= sheetX) {
				sheet.setX(sheetX - rightDiff - sheetLayoutParams.rightMargin);
				revealXDirection = RevealXDirection.LEFT;
			}
			// Otherwise, align the left side of the sheet with the left side of the FAB
			else if (leftDiff != 0 && leftDiff <= sheetX) {
				sheet.setX(sheetX - leftDiff + sheetLayoutParams.leftMargin);
				revealXDirection = RevealXDirection.RIGHT;
			}
		}
````

**Comment by gowong** [comment]
`sheet` is a view that your app passes in so you could just keep a reference to it in your subclass of `MaterialSheetAnimation`
