### ISSUE TITLE
Can you show example of having a normal FAB on one of the fragments?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [gowong/material-sheet-fab#4]
To show how it's best to transition between different FABs ...

**Comment by gowong** [comment]
Check out the sample app. It has examples of a FAB and how to show/hide it.
Let me know if there's something specific you're looking for.

**Comment by AndroidDeveloperLB** [comment]
I already tested it. It either has a FAB with menu, or hide it. 
What's the best way to transition between different FABs ?

**Comment by gowong** [comment]
Which transition are you referring to? Do you mean transitioning between FABs when swiping between tabs?

**Comment by AndroidDeveloperLB** [comment]
When you swipe between fragments, you can have this transiton of FABs
(animation when of the FAB itself when switching between fragments) :
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsVlhxNGJCNTEzNFU/components-buttons-fab-behavior_04_xhdpi_009.webm

**Comment by gowong** [comment]
I haven't implemented such a transition myself, but I imagine that you can get the effect you're after by using scale animations on two FABs, shrinking one FAB and expanding the other. Since this isn't a question about the library, you should post on StackOverflow so that other people can help you out.
